[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npm run start:dev"
healthcheckPath = "/health"
sleepApplication = false
multiRegionConfig = {
  "us-west2": {
    "numReplicas": 1
  }
}
restartPolicyType = "ON_FAILURE"
healthcheckTimeout = 300
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3 