import { Tag } from '../../../../src/tags/tags.entity';
import { Task } from '../../../../src/tasks/tasks.entity';

describe('Tag Entity', () => {
  // Factory function to create test tags
  const createTag = (overrides: Partial<Tag> = {}): Tag => {
    const tag = new Tag();
    tag.id = 'test-tag-id';
    tag.name = 'Test Tag';
    tag.color = '#FF0000';
    tag.description = 'Test Description';
    tag.createdAt = new Date();
    tag.updatedAt = new Date();

    // Apply any overrides
    Object.assign(tag, overrides);

    return tag;
  };

  describe('Basic Properties', () => {
    it('should create a tag with properties', () => {
      const tag = createTag();

      expect(tag.id).toBe('test-tag-id');
      expect(tag.name).toBe('Test Tag');
      expect(tag.color).toBe('#FF0000');
      expect(tag.description).toBe('Test Description');
      expect(tag.createdAt).toBeInstanceOf(Date);
      expect(tag.updatedAt).toBeInstanceOf(Date);
    });

    it('should set and get properties correctly', () => {
      const tag = createTag();

      // Update properties
      tag.name = 'Updated Tag';
      tag.color = '#00FF00';
      tag.description = 'Updated Description';

      // Check that properties were updated
      expect(tag.name).toBe('Updated Tag');
      expect(tag.color).toBe('#00FF00');
      expect(tag.description).toBe('Updated Description');
    });

    it('should handle nullable description', () => {
      const tag = createTag({ description: null });
      expect(tag.description).toBeNull();

      // Update description from null to a value
      tag.description = 'New description';
      expect(tag.description).toBe('New description');

      // Update description from a value to null
      tag.description = null;
      expect(tag.description).toBeNull();
    });

    it('should handle updatedAt property', () => {
      const tag = createTag();
      const initialUpdatedAt = tag.updatedAt;

      // In a real database operation, TypeORM would update this automatically
      // Here we simulate that behavior
      const newUpdatedAt = new Date(initialUpdatedAt.getTime() + 1000);
      tag.updatedAt = newUpdatedAt;

      expect(tag.updatedAt).toEqual(newUpdatedAt);
      expect(tag.updatedAt).not.toEqual(initialUpdatedAt);
    });

    it('should validate color format', () => {
      // This test checks that color follows hex format
      // Valid colors: #RRGGBB
      const validColors = [
        '#FF0000',
        '#00FF00',
        '#0000FF',
        '#FFFFFF',
        '#000000',
        '#123456',
      ];
      const tag = createTag();

      for (const color of validColors) {
        tag.color = color;
        expect(tag.color).toBe(color);
      }

      // In a real implementation, validation might happen at the application layer
      // or with class-validator decorators
    });
  });

  describe('Relationships', () => {
    it('should initialize tasks as undefined', () => {
      const tag = new Tag();
      expect(tag.tasks).toBeUndefined();
    });

    it('should handle tasks relationship', () => {
      const tag = createTag();
      const task1 = new Task();
      task1.id = 'task-1';
      task1.title = 'Task 1';

      const task2 = new Task();
      task2.id = 'task-2';
      task2.title = 'Task 2';

      // Simulate the many-to-many relationship
      tag.tasks = [task1, task2];

      expect(tag.tasks).toHaveLength(2);
      expect(tag.tasks[0].id).toBe('task-1');
      expect(tag.tasks[1].id).toBe('task-2');
    });

    it('should be able to add and remove tasks', () => {
      const tag = createTag();
      tag.tasks = [];

      const task1 = new Task();
      task1.id = 'task-1';

      const task2 = new Task();
      task2.id = 'task-2';

      // Add tasks to the tag
      tag.tasks.push(task1);
      tag.tasks.push(task2);

      expect(tag.tasks).toHaveLength(2);

      // Remove a task
      tag.tasks = tag.tasks.filter((task) => task.id !== 'task-1');

      expect(tag.tasks).toHaveLength(1);
      expect(tag.tasks[0].id).toBe('task-2');
    });
  });

  describe('Object Instantiation', () => {
    it('should create a new Tag instance', () => {
      const tag = new Tag();
      expect(tag).toBeInstanceOf(Tag);
    });

    it('should set default values when creating new instance', () => {
      const tag = new Tag();

      // ID will be generated by the database
      expect(tag.id).toBeUndefined();
      expect(tag.name).toBeUndefined();
      expect(tag.color).toBeUndefined();
      expect(tag.description).toBeUndefined();
      expect(tag.createdAt).toBeUndefined();
      expect(tag.updatedAt).toBeUndefined();
      expect(tag.tasks).toBeUndefined();
    });
  });
});
