name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run Tests
        run: npm test
        continue-on-error: true

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: 'Railway Deploy'
        description: 'Simple Action to Deploy Railway App using Railway CLI'
        inputs:
          railway_token:
            description: 'Railway Token for Deployment'
            required: false
          service:
            description: 'The specific service target'
            required: true
          detach:
            description: 'Detach option in the railway cli'
            required: false
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
          RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
        runs:
          args:
            - ${{ inputs.service }}
            - ${{ inputs.detach }}